name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}
        
    - name: Build and push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6.4
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}
        registry: ghcr.io
        repository: ${{ github.repository_owner }}/dotnet-windowsservercore
        tag_with_ref: true
        dockerfile: ./Dockerfile
        build_args: PFX_PASSWORD=${{ secrets.PFX_PASSWORD }}
